### ISSUE TITLE
Productionize private key provider

### ISSUE THREAD

**Issue by phbnf** [transparency-dev/static-ct#6]
Right now, the log private keys are provided in a private .pem file. Let's migrate this to a more robust key providing system. For GCP, let's use KMS.

We spoke about using Tink, but it's unclear what benefit it would bring in the immediate future.

**Comment by roger2hk** [comment]
As indicated in #36, GCP KMS signing costs too much for the CT ecosystem. We will explore the in-memory signing implementation.
